# MassGen Configuration
# Usage:
# uv run python -m massgen.cli --config massgen/configs/basic/single/single_gpt4o_audio_generation.yaml "Generate audio speech from the following text 'Today is a wonderful day to build something people love!'."
agents:
  - id: "gpt4o_agent1"
    backend:
      type: "openai"
      model: "gpt-4o"
      text:
        verbosity: "medium"
      # upload_files:
      #   - image_path: "/Users/danruiqi/Desktop/Danrui/Research/MassGen/git19/MassGen/massgen/configs/resources/v0.0.27-example/multimodality.jpg" # Example image to be used by the agent
      cwd: "workspace1"  # Working directory for file operations
      enable_image_generation: true  # Enable image generation tools

orchestrator:
    snapshot_storage: "snapshots"  # Directory to store workspace snapshots
    agent_temporary_workspace: "temp_workspaces"  # Directory for temporary agent workspaces

ui:
  display_type: "rich_terminal"
  logging_enabled: true
