# MassGen File Search Configuration
# Demonstrates OpenAI File Search for document retrieval and Q&A
# Usage:
#   uv run python -m massgen.cli --config massgen/configs/basic/single/single_gpt5nano_file_search.yaml "What is humanity's last exam score for OpenAI Deep Research? Also, provide details about the other models mentioned in the PDF?"

agent:
  id: "file_search_agent"
  backend:
    type: "openai"
    model: "gpt-5-nano"
    upload_files:
      - file_path: "https://cdn.openai.com/API/docs/deep_research_blog.pdf"
  system_message: |
    You are a helpful research assistant

ui:
  display_type: "rich_terminal"
  logging_enabled: true