version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: massgen-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API (optional)
    volumes:
      - ./.massgen/qdrant_storage:/qdrant/storage
    environment:
      # Optional: Configure memory limits
      - QDRANT__SERVICE__MAX_REQUEST_SIZE_MB=10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

# Usage:
# 1. Start Qdrant server:
#    docker-compose -f docker-compose.qdrant.yml up -d
#
# 2. Check status:
#    docker-compose -f docker-compose.qdrant.yml ps
#
# 3. View logs:
#    docker-compose -f docker-compose.qdrant.yml logs -f qdrant
#
# 4. Stop server:
#    docker-compose -f docker-compose.qdrant.yml down
#
# 5. Access Qdrant dashboard:
#    Open http://localhost:6333/dashboard in your browser
