# MassGen Configuration: Lesson Planner Comparison
# This demonstrates interoperability by comparing AG2 and LangGraph lesson planner implementations
#
# Usage:
#   massgen --config @examples/tools/custom_tools/interop/ag2_and_langgraph_lesson_planner.yaml "Create a lesson plan for photosynthesis"
#   uv run python -m massgen.cli --config @examples/tools/custom_tools/interop/ag2_and_langgraph_lesson_planner.yaml "Create a lesson plan for photosynthesis"
#
# Description:
#   This configuration provides access to both AG2 (AutoGen) and LangGraph lesson planning tools,
#   allowing you to compare different multi-agent framework approaches within MassGen.
#
#   AG2 Version:
#   - Uses AutoGen's nested chat architecture
#   - Multiple agents in group chat collaboration
#   - Demonstrates AutoGen → MassGen interoperability
#
#   LangGraph Version:
#   - Uses LangGraph's state graph architecture
#   - Sequential workflow with state management
#   - Demonstrates LangGraph → MassGen interoperability
#
# Requirements:
#   - pip install pyautogen langgraph langchain-openai langchain-core
#   - OPENAI_API_KEY environment variable must be set

agents:
  - id: "ag2_planner" # AG2 (AutoGen) implementation
    backend:
      type: "openai"
      model: "gpt-4o"
      custom_tools:
        - name: ["ag2_lesson_planner"]
          category: "education"
          path: "massgen/tool/_extraframework_agents/ag2_lesson_planner_tool.py"
          function: ["ag2_lesson_planner"]
    system_message: |
      You are an AI assistant with access to the AG2 (AutoGen) lesson planning tool.

      The ag2_lesson_planner tool creates comprehensive fourth-grade lesson plans using AutoGen's
      nested chat architecture with multiple collaborative agents.

      When users ask for a lesson plan, use the ag2_lesson_planner tool. After receiving the result,
      present it clearly and mention that this was generated using the AG2 (AutoGen) framework.

  - id: "langgraph_planner" # LangGraph implementation
    backend:
      type: "openai"
      model: "gpt-4o"
      custom_tools:
        - name: ["langgraph_lesson_planner"]
          category: "education"
          path: "massgen/tool/_extraframework_agents/langgraph_lesson_planner_tool.py"
          function: ["langgraph_lesson_planner"]
    system_message: |
      You are an AI assistant with access to the LangGraph lesson planning tool.

      The langgraph_lesson_planner tool creates comprehensive fourth-grade lesson plans using
      LangGraph's state graph architecture with sequential workflow nodes.

      When users ask for a lesson plan, use the langgraph_lesson_planner tool. After receiving the result,
      present it clearly and mention that this was generated using the LangGraph framework.

ui:
  display_type: "rich_terminal"
  logging_enabled: true
