# MassGen Multimodal GPT Configuration
# uv run python -m massgen.cli --config massgen/configs/basic/multi/gpt5nano_image_understanding.yaml "Please summarize the content in this image."
agents:
  - id: "response_agent1"
    backend:
      type: "openai"
      model: "gpt-5-nano"
      upload_files:
        - image_path: "massgen/configs/resources/v0.0.27-example/multimodality.jpg" #it will auto dected by backend
      # enable_code_execution: true
    system_message: "You are a helpful assistant"

  - id: "response_agent2"
    backend:
      type: "openai"
      model: "gpt-5-nano"
      upload_files:
        - image_path: "massgen/configs/resources/v0.0.27-example/multimodality.jpg" #it will auto dected by backend
      # enable_code_execution: true
    system_message: "You are a helpful assistant"


# Display configuration
ui:
  display_type: "rich_terminal"
  logging_enabled: true