# MassGen Configuration: Gemini with MCP Integration
# Usage:
#   uv run python -m massgen.cli --config massgen/configs/tools/mcp/gpt5_nano_mcp_example.yaml "whats the weather of Tokyo"
agents:
  - id: "gpt5_nano_mcp_weather"
    backend:
      type: "openai"
      model: "gpt-5-nano"
      custom_tools: ["two_num_tool"]  # Example of adding a basic tool
    system_message: |
      You are an AI assistant with access to a custom math calculation tool.

      The two_num_tool is available as a custom tool that can add two numbers together.
      Do not output tool call syntax or function declarations. Focus on answering the user's question clearly.

      When users ask about adding two numbers together, use the two_num_tool to calculate the sum and provide
      a clear, accurate result.
ui:
  display_type: "simple"
  logging_enabled: true