# MassGen Memory-Enabled Codebase Analysis Configuration
# This configuration demonstrates persistent memory usage for long-term knowledge retention
# across extensive codebase exploration tasks

agents:
  - id: "gpt-5-mini"
    backend:
      type: "openai"
      model: "gpt-5-mini"
      text:
        verbosity: "medium"
      reasoning:
        effort: "medium"
        summary: "auto"

    # Enable persistent memory for long-term knowledge retention
    persistent_memory:
      enabled: true
      agent_name: "codebase_analyzer_gpt5"
      user_name: "developer"
      on_disk: true

      # LLM config for memory operations (summarization, extraction)
      llm:
        backend_type: "openai"
        model: "gpt-5-mini"

      # Embedding config for semantic search
      embedding:
        backend_type: "openai"
        model: "text-embedding-3-small"

  - id: "gemini-2.5-flash"
    backend:
      type: "gemini"
      model: "gemini-2.5-flash"

    # Enable persistent memory
    persistent_memory:
      enabled: true
      agent_name: "codebase_analyzer_gemini"
      user_name: "developer"
      on_disk: true

      llm:
        backend_type: "gemini"
        model: "gemini-2.5-flash"

      embedding:
        backend_type: "openai"
        model: "text-embedding-3-small"

# Enable filesystem access for repository cloning and analysis
tools:
  filesystem:
    enabled: true
    allowed_operations:
      - "read_file"
      - "write_file"
      - "list_directory"
      - "search_files"
      - "create_directory"

    # Allow access to temporary workspace
    allowed_paths:
      - "./workspace"
      - "/tmp/massgen_workspace"

    # Prevent access to sensitive areas
    protected_paths:
      - "~/.ssh"
      - "~/.aws"
      - "/etc"

  command_line:
    enabled: true
    allowed_commands:
      - "git"
      - "ls"
      - "cat"
      - "grep"
      - "find"
      - "tree"

    # Prevent destructive operations
    blocked_commands:
      - "rm -rf"
      - "dd"
      - "mkfs"
      - "format"

ui:
  display_type: "rich_terminal"
  logging_enabled: true

# Orchestration settings for complex analytical tasks
orchestration:
  max_rounds: 5
  voting_enabled: true
  consensus_threshold: 0.6
