# Basic Command Execution with Auto-detect Virtual Environment
# Run with: uv run python -m massgen.cli --config massgen/configs/tools/code-execution/basic_command_execution.yaml "Write a Python function to calculate factorial and test it"

agent:
  id: "coder"
  backend:
    type: "openai"
    model: "gpt-4.1"
    cwd: "workspace"
    enable_mcp_command_line: true

  system_message: |
    You are a coding assistant with command line access.
    You can execute commands using the execute_command tool.

    Note: If the workspace has a .venv directory, it will be automatically used.

orchestrator:
  snapshot_storage: "snapshots"
  agent_temporary_workspace: "temp_workspaces"

ui:
  display_type: "rich_terminal"
  logging_enabled: true
