# Command Execution with Whitelist Filtering (Python/Testing Only)
# Run with: uv run python -m massgen.cli --config massgen/configs/tools/code-execution/command_filtering_whitelist.yaml "Write and test a sorting algorithm"

agent:
  id: "python_agent"
  backend:
    type: "openai"
    model: "gpt-4.1"
    cwd: "workspace"
    enable_mcp_command_line: true
    command_line_allowed_commands:
      - "python .*"
      - "python3 .*"
      - "pytest .*"
      - "pip .*"

  system_message: |
    You are a Python specialist with restricted command access.
    You can only run Python-related commands: python, pytest, pip.

    Use these tools to write, test, and verify your code.

orchestrator:
  snapshot_storage: "snapshots"
  agent_temporary_workspace: "temp_workspaces"

ui:
  display_type: "rich_terminal"
  logging_enabled: true
