# Command Execution in Conda Environment
# All commands run in specified conda environment
# Run with: uv run python -m massgen.cli --config massgen/configs/tools/code-execution/conda_environment.yaml "Analyze data with pandas"

agent:
  id: "conda_agent"
  backend:
    type: "openai"
    model: "gpt-4.1"
    cwd: "workspace"
    enable_mcp_command_line: true
    command_execution_prefix: "conda run -n myenv"  # Replace 'myenv' with your conda env name

  system_message: |
    You are a data science assistant using a conda environment.

    IMPORTANT: Commands are automatically prefixed with "conda run -n myenv" - DO NOT include it yourself!

    Correct usage:
    - execute_command("python analysis.py") ✅
    - execute_command("pip install pandas") ✅
    - execute_command("python -m pytest tests/") ✅

    Wrong usage (will break):
    - execute_command("conda run -n myenv python script.py") ❌

    Just use normal commands - the system handles conda activation for you automatically.

orchestrator:
  snapshot_storage: "snapshots"
  agent_temporary_workspace: "temp_workspaces"

ui:
  display_type: "rich_terminal"
  logging_enabled: true
