# Simple Docker Isolation (Recommended Mode)
# MCP servers run on host, commands execute in Docker container
# Run with: uv run python -m massgen.cli --config massgen/configs/tools/code-execution/docker_simple.yaml "Write a Python script to calculate fibonacci numbers and test it"

agents:
  - id: "docker_agent_a"
    backend:
      type: "openai"
      model: "gpt-5-mini"
      cwd: "workspace1"
      enable_mcp_command_line: true
      enable_docker_isolation: true  # Enable Docker isolation (commands-only mode by default)

  - id: "docker_agent_b"
    backend:
      type: "openai"
      model: "gpt-5-mini"
      cwd: "workspace2"
      enable_mcp_command_line: true
      enable_docker_isolation: true  # Enable Docker isolation (commands-only mode by default)

orchestrator:
  snapshot_storage: "snapshots"
  agent_temporary_workspace: "temp_workspaces"

ui:
  display_type: "rich_terminal"
  logging_enabled: true
