# Multi-Agent with Different Command Execution Permissions
# Coder has full access, Reviewer has read-only access
# Run with: uv run python -m massgen.cli --config massgen/configs/tools/code-execution/multi_agent_different_permissions.yaml "Write a web scraper and review it"

agents:
  - id: "coder"
    backend:
      type: "openai"
      model: "gpt-4.1"
      cwd: "workspace1"
      enable_mcp_command_line: true
      # Can run any command (with default safety checks)

    system_message: |
      You are a coder with full command access.
      Write code, install dependencies, run tests, and execute scripts.

      Default safety: rm -rf /, dd, fork bombs, sudo, chmod, chown are blocked.

  - id: "reviewer"
    backend:
      type: "gemini"
      model: "gemini-2.5-pro"
      cwd: "workspace2"
      enable_mcp_command_line: true
      # Read-only commands only
      command_line_allowed_commands:
        - "cat .*"
        - "ls .*"
        - "grep .*"
        - "python -c .*"  # Read-only Python evaluation

    system_message: |
      You review code and can run read-only commands.
      Use cat, ls, grep to inspect code. Use python -c for quick checks.

      You cannot modify files or install packages - focus on analysis.

orchestrator:
  snapshot_storage: "snapshots"
  agent_temporary_workspace: "temp_workspaces"

ui:
  display_type: "rich_terminal"
  logging_enabled: true
