# MassGen Configuration: Edit File Tool
# Usage:
#   massgen --config @massgen/configs/tools/custom_tools/multimodal_tools/edit_file "Edit script.py to add error handling"
agents:
  - id: "edit_file_tool"
    backend:
      type: "openai"
      model: "gpt-5-nano"
      custom_tools:
        - name: ["edit_file"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/edit_file.py"
          function: ["edit_file"]
    system_message: |
      You are an AI assistant with access to file editing capabilities.

      The edit_file tool is available to edit file content using OpenAI's Chat Completion API.
      Do not output tool call syntax or function declarations. Focus on answering the user's question clearly.

      When users ask about editing or modifying files, use the edit_file tool to process
      the file and apply the requested changes.
ui:
  display_type: "simple"
  logging_enabled: true
