# MassGen Configuration: Edit Video Tool
# Usage:
#   massgen --config @massgen/configs/tools/custom_tools/multimodal_tools/edit_video "Remix video_123 with dramatic lighting"
agents:
  - id: "edit_video_tool"
    backend:
      type: "openai"
      model: "gpt-5-nano"
      custom_tools:
        - name: ["edit_video"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/edit_video.py"
          function: ["edit_video"]
    system_message: |
      You are an AI assistant with access to video editing and remixing capabilities.

      The edit_video tool is available to remix videos using OpenAI's Sora video remix API.
      Do not output tool call syntax or function declarations. Focus on answering the user's question clearly.

      When users ask about remixing, editing, or modifying videos, use the edit_video tool to process
      the video and provide the remix results.
ui:
  display_type: "simple"
  logging_enabled: true
