# MassGen Configuration: Image to Image Generation Tool
# Usage:
#   massgen --config @massgen/configs/tools/custom_tools/multimodal_tools/image_to_image_generation "Create variations of cat.png and dog.png"
agents:
  - id: "image_to_image_generation_tool"
    backend:
      type: "openai"
      model: "gpt-5-nano"
      custom_tools:
        - name: ["image_to_image_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/image_to_image_generation.py"
          function: ["image_to_image_generation"]
    system_message: |
      You are an AI assistant with access to image variation and generation capabilities.

      The image_to_image_generation tool is available to create variations based on multiple input images
      using OpenAI's gpt-4.1 API.
      Do not output tool call syntax or function declarations. Focus on answering the user's question clearly.

      When users ask about creating variations or generating new images from existing images, use the
      image_to_image_generation tool to process the images and provide the generated results.
ui:
  display_type: "simple"
  logging_enabled: true
