# Multi-Agent Multimodal Generation Configuration
# This config demonstrates two agents collaborating on image, video, and audio generation tasks
# Usage:
#   massgen --config massgen/configs/basic/multi/multimodal_generation_two_agents.yaml "Generate an image of a sunset, then create a video based on it, and add background music."

agents:
  - id: "visual_generator"
    backend:
      type: "openai"
      model: "gpt-4o"
      text:
        verbosity: "medium"
      cwd: "workspace1"
      custom_tools:
        - name: ["text_to_image_generation", "image_to_image_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_image_generation.py"
          function: ["text_to_image_generation"]
        - name: ["image_to_image_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/image_to_image_generation.py"
          function: ["image_to_image_generation"]
        - name: ["text_to_video_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_video_generation.py"
          function: ["text_to_video_generation"]
        - name: ["text_add_image_to_video_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_add_image_to_video_generation.py"
          function: ["text_add_image_to_video_generation"]
        - name: ["video_to_video_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/video_to_video_generation.py"
          function: ["video_to_video_generation"]
    system_message: |
      You are a visual content specialist AI agent with expertise in image and video generation.

      You have access to the following multimodal generation tools:
      - text_to_image_generation: Generate images from text prompts (no input images)
      - image_to_image_generation: Create variations from input images
      - text_to_video_generation: Generate videos from text prompts (no input images)
      - text_add_image_to_video_generation: Generate videos from text and input images
      - video_to_video_generation: Generate new videos from input videos

      When users request visual content, use the appropriate tools to generate images or videos.
      You can collaborate with the audio_generator agent for audio-related tasks.

  - id: "audio_generator"
    backend:
      type: "openai"
      model: "gpt-4o"
      text:
        verbosity: "medium"
      cwd: "workspace2"
      custom_tools:
        - name: ["text_to_speech_continue_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_speech_continue_generation.py"
          function: ["text_to_speech_continue_generation"]
        - name: ["text_to_speech_transcription_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_speech_transcription_generation.py"
          function: ["text_to_speech_transcription_generation"]
        - name: ["audio_to_audio_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/audio_to_audio_generation.py"
          function: ["audio_to_audio_generation"]
        - name: ["text_to_file_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_file_generation.py"
          function: ["text_to_file_generation"]
    system_message: |
      You are an audio content specialist AI agent with expertise in audio and speech generation.

      You have access to the following multimodal generation tools:
      - text_to_speech_continue_generation: Generate speech audio from text using gpt-4o-audio-preview
      - text_to_speech_transcription_generation: Convert transcriptions to speech using TTS API
      - audio_to_audio_generation: Process multiple audio files (transcribe, synthesize, generate)
      - text_to_file_generation: Generate text documents (TXT, MD, PDF)

      When users request audio content or speech synthesis, use the appropriate tools to generate audio.
      You can collaborate with the visual_generator agent for image/video-related tasks.

orchestrator:
  snapshot_storage: "snapshots"
  agent_temporary_workspace: "temp_workspaces"
  context_paths:
    - path: "massgen/configs/resources/"
      permission: "read"
    - path: "workspace1"
      permission: "read_write"
    - path: "workspace2"
      permission: "read_write"

# UI Configuration
ui:
  display_type: "rich_terminal"
  logging_enabled: true
