# Multi-Agent Collaborative Multimodal Generation Configuration
# This config demonstrates two agents with full access to all image, video, and audio generation tools
# Usage:
#   massgen --config massgen/configs/basic/multi/multimodal_generation_collaborative.yaml "Create a promotional video with background music and save the script as PDF."

agents:
  - id: "multimodal_agent_1"
    backend:
      type: "openai"
      model: "gpt-4o"
      text:
        verbosity: "medium"
      cwd: "workspace1"
      custom_tools:
        # Image Generation Tools
        - name: ["text_to_image_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_image_generation.py"
          function: ["text_to_image_generation"]
        - name: ["image_to_image_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/image_to_image_generation.py"
          function: ["image_to_image_generation"]
        # Video Generation Tools
        - name: ["text_to_video_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_video_generation.py"
          function: ["text_to_video_generation"]
        - name: ["text_add_image_to_video_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_add_image_to_video_generation.py"
          function: ["text_add_image_to_video_generation"]
        - name: ["video_to_video_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/video_to_video_generation.py"
          function: ["video_to_video_generation"]
        # Audio Generation Tools
        - name: ["text_to_speech_continue_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_speech_continue_generation.py"
          function: ["text_to_speech_continue_generation"]
        - name: ["text_to_speech_transcription_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_speech_transcription_generation.py"
          function: ["text_to_speech_transcription_generation"]
        - name: ["audio_to_audio_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/audio_to_audio_generation.py"
          function: ["audio_to_audio_generation"]
        # File Generation Tool
        - name: ["text_to_file_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_file_generation.py"
          function: ["text_to_file_generation"]
    system_message: |
      You are a versatile multimodal AI agent capable of generating images, videos, audio, and documents.

      You have access to all multimodal generation tools:

      IMAGE GENERATION:
      - text_to_image_generation: Generate images from text prompts
      - image_to_image_generation: Create variations from input images

      VIDEO GENERATION:
      - text_to_video_generation: Generate videos from text prompts
      - text_add_image_to_video_generation: Generate videos from text and images
      - video_to_video_generation: Generate new videos from input videos

      AUDIO GENERATION:
      - text_to_speech_continue_generation: Generate speech from text (gpt-4o-audio-preview)
      - text_to_speech_transcription_generation: Convert text to speech (TTS API)
      - audio_to_audio_generation: Process and synthesize multiple audio files

      DOCUMENT GENERATION:
      - text_to_file_generation: Generate documents (TXT, MD, PDF)

      Use these tools to fulfill user requests for multimodal content generation.
      You can collaborate with multimodal_agent_2 for complex tasks requiring parallel processing.

  - id: "multimodal_agent_2"
    backend:
      type: "openai"
      model: "gpt-4o"
      text:
        verbosity: "medium"
      cwd: "workspace2"
      custom_tools:
        # Image Generation Tools
        - name: ["text_to_image_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_image_generation.py"
          function: ["text_to_image_generation"]
        - name: ["image_to_image_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/image_to_image_generation.py"
          function: ["image_to_image_generation"]
        # Video Generation Tools
        - name: ["text_to_video_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_video_generation.py"
          function: ["text_to_video_generation"]
        - name: ["text_add_image_to_video_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_add_image_to_video_generation.py"
          function: ["text_add_image_to_video_generation"]
        - name: ["video_to_video_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/video_to_video_generation.py"
          function: ["video_to_video_generation"]
        # Audio Generation Tools
        - name: ["text_to_speech_continue_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_speech_continue_generation.py"
          function: ["text_to_speech_continue_generation"]
        - name: ["text_to_speech_transcription_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_speech_transcription_generation.py"
          function: ["text_to_speech_transcription_generation"]
        - name: ["audio_to_audio_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/audio_to_audio_generation.py"
          function: ["audio_to_audio_generation"]
        # File Generation Tool
        - name: ["text_to_file_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_file_generation.py"
          function: ["text_to_file_generation"]
    system_message: |
      You are a versatile multimodal AI agent capable of generating images, videos, audio, and documents.

      You have access to all multimodal generation tools:

      IMAGE GENERATION:
      - text_to_image_generation: Generate images from text prompts
      - image_to_image_generation: Create variations from input images

      VIDEO GENERATION:
      - text_to_video_generation: Generate videos from text prompts
      - text_add_image_to_video_generation: Generate videos from text and images
      - video_to_video_generation: Generate new videos from input videos

      AUDIO GENERATION:
      - text_to_speech_continue_generation: Generate speech from text (gpt-4o-audio-preview)
      - text_to_speech_transcription_generation: Convert text to speech (TTS API)
      - audio_to_audio_generation: Process and synthesize multiple audio files

      DOCUMENT GENERATION:
      - text_to_file_generation: Generate documents (TXT, MD, PDF)

      Use these tools to fulfill user requests for multimodal content generation.
      You can collaborate with multimodal_agent_1 for complex tasks requiring parallel processing.

orchestrator:
  snapshot_storage: "snapshots"
  agent_temporary_workspace: "temp_workspaces"
  context_paths:
    - path: "massgen/configs/resources/"
      permission: "read"
    - path: "workspace1"
      permission: "read_write"
    - path: "workspace2"
      permission: "read_write"

# UI Configuration
ui:
  display_type: "rich_terminal"
  logging_enabled: true
