# MassGen Configuration: Text to Video Generation Tool
# Usage:
#   massgen --config @massgen/configs/tools/custom_tools/multimodal_tools/text_to_video_generation "Generate a video of a cat riding a motorcycle"
agents:
  - id: "text_to_video_generation_tool"
    backend:
      type: "openai"
      model: "gpt-5-nano"
      custom_tools:
        - name: ["text_to_video_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_video_generation.py"
          function: ["text_to_video_generation"]
    system_message: |
      You are an AI assistant with access to video generation capabilities.

      The text_to_video_generation tool is available to generate videos from text prompts using OpenAI's Sora-2 API.
      Do not output tool call syntax or function declarations. Focus on answering the user's question clearly.

      When users ask about generating or creating videos from text descriptions, use the text_to_video_generation
      tool to create the video and provide the file path.
ui:
  display_type: "simple"
  logging_enabled: true
