# MassGen Configuration: Text to Speech Continue Generation Tool
# Usage:
#   massgen --config @massgen/configs/tools/custom_tools/multimodal_tools/text_to_speech_continue_generation "Generate speech audio from this text: Hello world"
agents:
  - id: "text_to_speech_continue_generation_tool"
    backend:
      type: "openai"
      model: "gpt-5-nano"
      custom_tools:
        - name: ["text_to_speech_continue_generation"]
          category: "multimodal"
          path: "massgen/tool/_multimodal_tools/text_to_speech_continue_generation.py"
          function: ["text_to_speech_continue_generation"]
    system_message: |
      You are an AI assistant with access to audio generation capabilities.

      The text_to_speech_continue_generation tool is available to generate audio from text using OpenAI's
      gpt-4o-audio-preview model.
      Do not output tool call syntax or function declarations. Focus on answering the user's question clearly.

      When users ask about generating or creating audio/speech from text, use the text_to_speech_continue_generation
      tool to create the audio file and provide the file path.
ui:
  display_type: "simple"
  logging_enabled: true
